export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST'
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS'
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR'

export const FETCH_CURRENT_NEWS_REQUEST = 'FETCH_CURRENT_NEWS_REQUEST'
export const FETCH_CURRENT_NEWS_SUCCESS = 'FETCH_CURRENT_NEWS_SUCCESS'
export const FETCH_CURRENT_NEWS_ERROR = 'FETCH_CURRENT_NEWS_ERROR'

export const FETCH_CURRENT_COMMENTS_REQUEST = 'FETCH_CURRENT_COMMENTS_REQUEST'
export const FETCH_CURRENT_COMMENTS_SUCCESS = 'FETCH_CURRENT_COMMENTS_SUCCESS'
export const FETCH_CURRENT_COMMENTS_ERROR = 'FETCH_CURRENT_COMMENTS_ERROR'
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS'
