export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST'
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS'
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR'

export const FETCH_CURRENT_NEWS_REQUEST = 'FETCH_CURRENT_NEWS_REQUEST'
export const FETCH_CURRENT_NEWS_SUCCESS = 'FETCH_CURRENT_NEWS_SUCCESS'
export const FETCH_CURRENT_NEWS_ERROR = 'FETCH_CURRENT_NEWS_ERROR'

export const FETCH_CURRENT_COMMENTS_REQUEST = 'FETCH_CURRENT_COMMENTS_REQUEST'
export const FETCH_CURRENT_COMMENTS_SUCCESS = 'FETCH_CURRENT_COMMENTS_SUCCESS'
export const FETCH_CURRENT_COMMENTS_ERROR = 'FETCH_CURRENT_COMMENTS_ERROR'

export const FETCH_COMMENTS_BY_ID_REQUEST = 'FETCH_COMMENTS_BY_ID_REQUEST'
export const FETCH_COMMENTS_BY_ID_SUCCESS = 'FETCH_COMMENTS_BY_ID_SUCCESS'
export const FETCH_COMMENTS_BY_ID_ERROR = 'FETCH_COMMENTS_BY_ID_ERROR'
